### ISSUE TITLE
thread 'tokio-runtime-worker' panicked at src/decode_call.rs:119:14:

### ISSUE THREAD

**Issue by witimdoti** [enviodev/hypersync-client-python#33]
for this on avalanche 
i'm working on python

- function signature 0x38ed1739 
- tx_hash : 0xabeff83ff28f8b9369febdd196ade470181dc2527b84844e8456e57e82f13756

 decoded_input = await CallDecoder([
            "swapExactTokensForTokens(uint256 amountIn, uint256 amountOutMin, address[] path, address to, uint256 deadline)"
        ]).decode_transactions_input([res.data.transactions])
        
i have this one 

[ERROR] Failed to decode input for transaction 0xabeff83ff28f8b9369febdd196ade470181dc2527b84844e8456e57e82f13756: rust future panicked: unknown error

thread 'tokio-runtime-worker' panicked at src/decode_call.rs:119:14:
called `Result::unwrap()` on an `Err` value: decode log

Caused by:
    0: decoding input data
    1: buffer overrun while deserializing
    2: buffer overrun while deserializing
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'tokio-runtime-worker' panicked at src/decode_call.rs:61:14:
called `Result::unwrap()` on an `Err` value: JoinError::Panic(Id(19), ...)

**Comment by mnmnk43434** [comment]
Hello, we tried to solve the issue.

This is what we did:

Modify the decode_impl function to handle potential errors when decoding transaction input. This change will prevent panics and return None when decoding fails.

You can review changes in this commit: https://github.com/mnmnk43434/enviodev-hypersync-client-python-33/commit/1b9dbe786731047afa727ad44488da8b688e2c23.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.

**Comment by JasoonS** [comment]
Hi @witimdoti

Thanks for reporting. Sorry for the slow response.

With Arrow unfortunately at the moment we do not support  deserializing log arguments that are arrays, structs or tuples.

We are looking to implement this though as another user also has mentioned this issue. We will keep you updated when it is fixed.
